spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.87.10.4:3306/OBDGTNDESA
    username: obdgtndesa
    password: Mygtn2022#
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        default_schema: OBDGTNDESA

app:
  nombreProyecto: proyectoBase
  rest:
    endpoints: 
      ruta1: /ruta1
      ruta2: /ruta2
      buscarAutobusId: /autobus/{id}

################################################################################
## LOGGER
################################################################################
logging:
  file.name: C:\tmp/${app.nombreProyecto}/${app.nombreProyecto}.log
  file.path: C:\tmp/${app.nombreProyecto}/logs/ # ${RUTA}/logs/
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: ERROR
    com.minsait: TRACE

   

