spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/EMTBBDD
    username: coches
    password: uxOo_YhJXzxAF3uZ
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        default_schema: EMTBBDD

app:
  nombreProyecto: proyectoBase
  rest:
    endpoints: 
      ruta1: /ruta1
      ruta2: /ruta2
      buscarAutobusId: /autobus/{id}
      save: /save
      create: /create
      listarAutobusMarca: /listar/{marcas}
      login: /login
      buscarConductorNum: /conductor/{numeroEmpleado}


################################################################################
## LOGGER
################################################################################
logging:
  file.name: C:\tmp/${app.nombreProyecto}/${app.nombreProyecto}.log
  file.path: C:\tmp/${app.nombreProyecto}/logs/ # ${RUTA}/logs/
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: ERROR
    com.minsait: TRACE

   

